name: Soar Education
favicon: null
layout_spectrum: 0.792229
typography_spectrum: 0.63375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#0098C9'
    - '#565F68'
    - '#44BAF8'
    - '#94D2F2'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.856418
  rhythmicContrast: 0.212837
purpose: []
