analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#0098C9'
    - '#565F68'
    - '#44BAF8'
    - '#94D2F2'
  brandStrength: 0.875
  lightness: 0.5
  rhythmicContrast: 0.13085
  saturation: 0.689189
cta: {}
layout_spectrum: 0.792229
name: Soar Education
opengraph: {}
purpose: []
typography_spectrum: 0.63375
